version: 2

project_name: remote-notifier

builds:
  - builder: rust
    tool: cross
    command: build
    targets:
      - x86_64-apple-darwin
      - aarch64-apple-darwin

archives:
  - formats: [tar.gz]

brews:
  - repository:
      owner: hirotake111
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
