version: 2

project_name: remote-notifier

builds:
  - binary: remote-notifier
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz

brews:
  - owner: hirotake111
    name: remote-notifier
    repo: homebrew-tap
