version: 2

project_name: remote-notifier

builds:
  - binary: remote-notifier
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    build_hook: ./build-hook.sh

archives:
  - formats: [tar.gz]

brews:
  - repository:
      owner: hirotake111
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
